version: '3.8'

# Dockerized deployment for Servobill
# Includes: Postgres, Queue Workers, Next.js App, FusionAuth

services:
  # ---
  # Postgres connection URL for local development:
  # postgres://servobill:servobill@localhost:5432/servobill
  # Format: postgres://<user>:<password>@<host>:<port>/<database>
  # ---
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: servobill-postgres
    environment:
      POSTGRES_USER: servobill-user
      POSTGRES_PASSWORD: servobill-password
      POSTGRES_DB: servobill-db
    volumes:
      - postgres-data:/var/lib/postgresql/data



  # # === FusionAuth Service ===
  # # Untested - for authentication without google auth https://fusionauth.io/download possible alternative: https://www.authelia.com, https://goauthentik.io
  # fusionauth:
  #   image: fusionauth/fusionauth-app:latest
  #   container_name: servobill-fusionauth
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: jdbc:postgresql://postgres:5432/servobill-db
  #     DATABASE_ROOT_USERNAME: servobill-user
  #     DATABASE_ROOT_PASSWORD: servobill-password
  #     DATABASE_USERNAME: servobill-user
  #     DATABASE_PASSWORD: servobill-password
  #     FUSIONAUTH_APP_MEMORY: 512M
  #     FUSIONAUTH_APP_RUNTIME_MODE: development
  #     FUSIONAUTH_APP_URL: http://localhost:9011
  #     FUSIONAUTH_SEARCH_TYPE: database
  #   ports:
  #     - "9011:9011"
  #   volumes:
  #     - fusionauth-config:/usr/local/fusionauth/config

  # === Queue Workers ===
  workers:
    build:
      context: ../..
      dockerfile: BackgroundJobs.Dockerfile
    container_name: servobill-queue-workers
    environment:
      # Inter service communication/configuration
      POSTGRES_URL: postgres://servobill-user:servobill-password@postgres:5432/servobill-db
      ENDPOINT_EVENTBRIDGE: http://queue-workers:9326

      # Email related settings
      SMTP_HOST: please-set
      SMTP_PORT: please-set
      SMTP_USER: please-set
      SMTP_PASSWORD: please-set
      SMTP_FROM: please-set
      SMTP_FROM_NAME: please-set
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - s3-data:/data

  # === Next.js Application ===
  app:
    build:
      context: ../..
      dockerfile: App.Dockerfile
    container_name: servobill-app
    environment:
      # Inter service communication/configuration
      POSTGRES_URL: postgres://servobill-user:servobill-password@postgres:5432/servobill-db
      ENDPOINT_EVENTBRIDGE: http://queue-workers:9326

      # Remove this once you actually put this behind an tls termination proxy
      INSECURE_COOKIES: true

      # Authentication related settings
      # ALLOWED_EMAILS: please-set
      # OAUTH_CLIENT_ID: please-set
      # JWT_SECRET: please-set

     


      # set this to the domain or path that is routed to the app:
      NEXT_PUBLIC_API_URL: http://localhost:3000/

    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - s3-data:/data

volumes:
  postgres-data: {}
  s3-data: {}
  # fusionauth-config: {} 