version: '3.8'

# Release Docker Compose for Servobill
# Loads environment variables from .env file (docker-compose does this automatically)
# Uses pre-built images tagged with the latest major version

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: servobill-postgres
    environment:
      POSTGRES_USER: servobill-user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: servobill-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  workers:
    image: ghcr.io/kellertobias/servobill/workers:v1
    container_name: servobill-queue-workers
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      UPLOAD_DIRECTORY: "/data"
      ENDPOINT_EVENTBRIDGE: http://workers:9326
      POSTGRES_URL: postgres://servobill-user:${DB_PASSWORD}@postgres:5432/servobill-db
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_FROM_NAME: ${SMTP_FROM_NAME}
    depends_on:
      - postgres
    working_dir: /app
    volumes:
      - ./data:/data

  app:
    image: ghcr.io/your-username/servobill/app:v1
    container_name: servobill-app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      UPLOAD_DIRECTORY: "/data"
      ENDPOINT_EVENTBRIDGE: http://workers:9326
      INSECURE_COOKIES: ${INSECURE_COOKIES:-false}
      POSTGRES_URL: postgres://servobill-user:${DB_PASSWORD}@postgres:5432/servobill-db
      ALLOWED_EMAILS: ${ALLOWED_EMAILS:-}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${PORT}:3000"
    depends_on:
      - postgres
    volumes:
      - ./data:/data

volumes:
  postgres-data: {} 