name: Production Workflow

on:
  push:
    branches:
      - live

env:
  NODE_ENV: "production"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Install modules
      run: NODE_ENV=development && npm ci

    - name: Lint
      run: npm run lint
    
    - name: Setup AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION
        aws configure set region $AWS_DEFAULT_REGION
        aws --version
    - name: Download Layers
      run: |
        ./stack/setup-layers-prod.sh
    - name: Build & Deploy
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        ALLOWED_EMAILS: ${{ secrets.ALLOWED_EMAILS }}
        OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
        HOSTED_ZONE_DOMAIN_NAME: ${{ secrets.HOSTED_ZONE_DOMAIN_NAME }}
        SITE_DOMAIN: ${{ secrets.SITE_DOMAIN }}
        OTEL_ENDPOINT: ${{ secrets.OTEL_ENDPOINT }}
        OTEL_HEADERS: ${{ secrets.OTEL_HEADERS }}
        LOGS_ENDPOINT: ${{ secrets.LOGS_ENDPOINT }}
        LOGS_HEADERS: ${{ secrets.LOGS_HEADERS }}
      run: |
        npm run gql:type
        npx sst deploy --stage prod

   